DROP TABLE EMP01;
CREATE TABLE EMP01 AS SELECT * FROM EMP; -- EMP테이블의 내용과 같은 EMP01생성
SELECT * FROM EMP01; -- 14행
INSERT INTO EMP01 SELECT * FROM EMP01; -- 데이터 뻥튀기 1번(28), 2번(56)
SELECT COUNT(*) FROM EMP01; -- EMP01의 행수
INSERT INTO EMP01 SELECT * FROM EMP01; --  11번(11만)
SELECT COUNT(*) FROM EMP01; -- 11만4천행정도

INSERT INTO EMP01 (EMPNO, ENAME, DEPTNO) VALUES (1111, 'HONG', 50);
INSERT INTO EMP01 SELECT * FROM EMP01; 

SELECT COUNT(*) FROM EMP01;

SELECT * FROM EMP01 WHERE ENAME = 'HONG';


-- 인덱스 생성

CREATE INDEX IDX_EMP0_ENAME ON EMP01(ENAME);
SELECt * FROM EMP01 WHERE ENAME='HONG';


COMMIT;

INSERT INTO EMP01 SELECT * FROM EMP01;

SELECT COUNNT(*) FROM EMP01;

